server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: Db.150029
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hrsys3?serverTimezone=UTC&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 3000000
      connection-test-query: select 1
mybatis:
  mapper-locations: classpath:mapper/*.xml